config/routes.rb
Rails.application.routes.draw do


  resources :users
  resources :friends
  resources :contacts
  resources :friend_requests
  get 'friends/index'
  get 'friends/destroy'


  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :user
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }


  validate :not_friends
  validate :not_pending
  
  private

  def not_friends
    errors.add(:friend, 'is already added') if user.friends.include?(friend)
  end

  def not_pending
    errors.add(:friend, 'already requested friendship') if friend.pending_friends.include?(user)
  end

  def accept
    user.friends << friend
    destroy
  end

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  after_create :create_inverse_relationship
  after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validate :not_self

  private
  
  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end

  def create_inverse_relationship
    friend.friendships.create(friend: user)
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end
end

app/models/user.rb
class User < ApplicationRecord
    
     #Relationships
     has_many :contacts
     has_many :friend_requests, dependent: :destroy
     has_many :pending_friends, through: :friend_requests, source: :friend

     has_many :friendships, dependent: :destroy
     has_many :friends, through: :friendships

     def remove_friend(friend)
          current_user.friends.destroy(friend)
     end

 

     #Password validation
     has_secure_password
 
     #To make sure user is filling out the whole form
     validates :username, :lastname, :firstname, :password_digest, presence: true 
     validates :password_digest, confirmation: true 
     validates :username, length: { in: 6..12 } 
     validates :username, uniqueness: true 
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authenticated

    def current_user
        if session[:user_id]
            @user = User.find(session[:user_id])
        else

        end

    end

    
    def logged_in?
        !!current_user
    end

    def authenticated 
        # redirect_to '/login' unless logged_in?
    end
    
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

    before_action :current_user, only: [:show, :edit, :update, :destroy]
    before_action :kind, only: [:new, :edit, :update, :destroy]
    
    def index
        @contacts = current_user.contacts    
    end

    def show
        @contacts = current_user.contacts
    end
    
    def new
        @user = User.find(session[:user_id])
        @contact = Contact.new
    end
    
    
    def create
        @contact = Contact.create(contacts_params)
        @user = User.find(session[:user_id])
        redirect_to @user
    end
    
      def edit
        @contact = Contact.find(params[:id])
      end
    
      def update
        @contact = Contact.find(params[:id])
        @contact.update(contacts_params)
        redirect_to @user
      end
    
      def destroy
        @contact = Contact.find(params[:id])
        @contact.destroy
        redirect_to @user
      end

      def kind
        @kind = ["Phone", "Email", "Website", "Linkedin", "Facebook", "Instagram", "Twitter"]
      end
    
    private
    
      def current_user
        @user = User.find(session[:user_id])
      end

      def current_contact
        @contact = Contact.find(params[:user_id])
      end
      
    
      def contacts_params
        params.require(:contact).permit(:kind, :value, :user_id)
      end

    end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController

    before_action :set_friend_request, except: [:index, :create]

    


    def index
        @incoming = FriendRequest.where(friend: current_user)
        @outgoing = current_user.friend_requests
    end

    def destroy
        @friend_request.destroy
        head :no_content
    end

    def update
        @friend_request.accept
        head :no_content
    end

    def create
        friend = User.find(params[:friend_id])
        @friend_request = current_user.friend_requests.new(friend: friend)

        if @friend_request.save
        render :show, status: :created, location: @friend_request
        else
        render json: @friend_request.errors, status: :unprocessable_entity
        end
    end


  private

  def set_friend_request
    @friend_request = FriendRequest.find(params[:id])
  end


end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    
    before_action :set_friend, only: :destroy

    

    def index
      @friends = current_user.friends
      @bla = current_user
    end

    def destroy
        current_user.remove_friend(@friend)
        head :no_content
    end


    private
  
    def set_friend
      @friend = current_user.friends.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  
skip_before_action :authenticated, only: [:new, :create]

def new
end



def create 
  @user = User.find_by(username:params[:username])
  session[:user_id] = @user.id

  if @user.authenticate(params[:password])
    redirect_to @user
  else
    redirect_to '/login'
  end
end


def destroy 
  session.delete(:user_id)
  redirect_to '/login'
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  before_action :current_user, only: [:show, :edit, :update]
  skip_before_action :authenticated, only: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(session[:user_id])
    @contacts = current_user.contacts
  end


  def new
    @users = User.all
    @user = User.new
  end


  def create
    @user = User.new(users_params)
    if @user.valid?
      @user.save
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user.update(users_params)
    redirect_to @user
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

private

  def current_user
    @user = User.find(session[:user_id])
  end
  

  def users_params
    params.require(:user).permit(:username, :password, :password_confirmation, :firstname, :lastname)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact do | f | %>
<%=f.label :Contact_Type %>
<%= f.collection_select :kind, @kind, :to_s, :to_s, include_blank: false %>
<%= f.label :Contact_Value %>
<%=f.text_field :value %>
<%= f.hidden_field :user_id, :value => @user.id %>
<%=f.submit %>
<%end%>

<%= console %>

app/views/contacts/edit.html.erb
<%= render 'form' %>

<%= link_to 'delete', url_for(action: :destroy, id: @contact), method: :delete, data: {confirm: 'Please,  no'}%>

app/views/contacts/index.html.erb
<br><br><br><% @contacts.each do |i| %>
<li>
<%= link_to i.value, contact_path(i) %><br>
</li>
<% end %>

app/views/contacts/new.html.erb
<%= render 'form' %>

app/views/contacts/show.html.erb
<br><br><br>
<%= tag.h4 "Hello: #{@user.firstname}" %>
<% @contacts.each do |i| %>
<li>
<%= i.kind %>:
<%= link_to i.value, edit_contact_path(i) %>
</li>
<% end %>

<br><br><br>

<%= form_with url:'/logout', method: 'delete' do |f| %>

<%= f.submit "Logout" %>

<% end %>

<%= console %>

app/views/friend_requests/index.html.erb
<h1>Friends#index</h1>

<%= console %>

app/views/friends/destroy.html.erb
<h1>Friends#destroy</h1>
<p>Find me in app/views/friends/destroy.html.erb</p>

app/views/friends/index.html.erb
<h1>Friends#index</h1>
<p>Find me in app/views/friends/index.html.erb</p>
<%= console %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= f.label :new_user %><br>
<%= f.text_field :username %><br>
<%= f.text_field :password %><br>
<%= f.text_field :firstname %><br>
<%= f.text_field :lastname %><br>


<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h3>Edit User</h3>
<br>


<%= form_for @user do |f| %>
<p> 
Username: <br>
<%= f.text_field :username %><br><br>
Password:<br>
<%= f.password_field :password %><br><br>
Confirm Password:<br>
<%= f.text_field :password_confirmation %><br><br>
First Name:<br>
<%= f.text_field :firstname %><br><br>
Last Name:<br>
<%= f.text_field :lastname %><br><br>
<p>

<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users:</h1>
<% @users.each do |i| %>
<li>
    <%= link_to i.firstname, user_path(i.id) %>
 </li>
<% end %>

app/views/users/new.html.erb
<% if flash[:errors]%>

<% flash[:errors].each do |error|%>
  <%= error %>
<% end %>
<% end %>


<%= form_for @user do |f| %>

<%= f.label :first_name %>
<%= f.text_field :firstname %>
<%= tag.br %>

<%= f.label :last_name %>
<%= f.text_field :lastname %>
<%= tag.br %>

<%= f.label :username %>
<%= f.text_field :username%>
<%= tag.br %>

<%= f.label :password %>
<%= f.password_field :password %>
<%= tag.br %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= tag.br %>

<%= f.submit "Register"%>
<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<title>W3.CSS Template</title>

    <!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="/login" class="w3-bar-item w3-button w3-padding-large">HOME</a>
    <a href="/users/profile" class="w3-bar-item w3-button w3-padding-large w3-hide-small">PROFILE</a>
    <a href="#contact" class="w3-bar-item w3-button w3-padding-large w3-hide-small">CONTACT</a>
    <!DOCTYPE html>
<html lang="en">
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.mySlides {display: none}
</style>
<body>
    
    

    <a href="javascript:void(0)" class="w3-padding-large w3-hover-red w3-hide-small w3-right"><i class="fa fa-search"></i></a>
  </div>
</div>  

<br><br><br>



<h1> <%= @user.firstname %> <%= @user.lastname %></h1>
    <br>
<h2>Contacts:</h2>
<br>

<h5>
<% @contacts.each do |i| %>
<li>
<%= i.kind %>:
<%= link_to i.value, edit_contact_path(i) %>
</li>
<% end %>
</h5>

    



<br><br><br><br>
<button class="button" style="vertical-align:middle"><span>Add Contact</span><a href='/contacts/new'></a> <br><br></button>
<%= form_with url:'/logout', method: 'delete' do |f| %>
<button class="button" style="vertical-align:middle"> <span><%= f.submit "Logout" %> </span></button>
<% end %>

<%= @friend_request %>
<%= console %>


<style>
.button {

  display: inline-block;
  
  border-radius: 4px;
  background-color: #f4511e;
  border: none;
  color: #FFFFFF;
  text-align: center;
  display: inline-block;
  padding: 15px 30px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}

.button span {
    font-size: 20px;
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}

h1 {
    color: red;
    align: center;
}
</style>